// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5EMBYB7ODBA4p_ur5uNEuasDQly2_Liw',
    appId: '1:95858401534:web:REPLACE_WITH_YOUR_WEB_APP_ID',
    messagingSenderId: '95858401534',
    projectId: 'envapp-7400e',
    authDomain: 'envapp-7400e.firebaseapp.com',
    storageBucket: 'envapp-7400e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5EMBYB7ODBA4p_ur5uNEuasDQly2_Liw',
    appId: '1:95858401534:android:a04a793c15d5f2254d85af',
    messagingSenderId: '95858401534',
    projectId: 'envapp-7400e',
    storageBucket: 'envapp-7400e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5EMBYB7ODBA4p_ur5uNEuasDQly2_Liw',
    appId: '1:95858401534:ios:REPLACE_WITH_YOUR_IOS_APP_ID',
    messagingSenderId: '95858401534',
    projectId: 'envapp-7400e',
    storageBucket: 'envapp-7400e.firebasestorage.app',
    iosBundleId: 'com.mapper.app',
  );
}
